/*
///////
#Opportunities By Status 
//////
*/

SELECT 
OPP_CATEGORY,
COUNT(DISTINCT OPPORTUNITY_ID) as Opps_Count,
CATEGORY_SORT
FROM (
SELECT 
FISCAL_QUARTER,
REVENUE_LINE_ID,
OPPORTUNITY_ID,
PIPELINE_K,
CASE
    WHEN OPPORTUNITY_STATUS IN ('Closed','Pending Cancel','Lost') THEN 'Lost/Closed' 
    WHEN OPPORTUNITY_STATUS IN ('Won','Won Pending') THEN 'Won' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (10,0)  THEN 'Open 10%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (20,30)  THEN 'Open 20-30%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (40,50)  THEN 'Open 40-50%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (60,70,80,90,100)  THEN 'Open 60%+' 
    ELSE 'Error' 
END AS Opp_Category,
CASE
    WHEN OPPORTUNITY_STATUS IN ('Closed','Pending Cancel','Lost') THEN 1
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (10,0)  THEN 2
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (20,30)  THEN 3
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (40,50)  THEN 4
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (60,70,80,90,100)  THEN 5
    WHEN OPPORTUNITY_STATUS IN ('Won','Won Pending') THEN 6
    ELSE 0 
END AS Category_Sort
FROM LATEST_PIPE P
LEFT JOIN FLM_SALES S on S.REP = P.TERRITORY_OWNER_EMAIL
WHERE PRIMARY_CAMPAIGN_SOURCE_CODE = :P3_CODE AND (:P1_VP = S.VP OR :P1_VP = '<All>') AND (:P1_DIR = S.DIR OR :P1_DIR = '<All>') AND (:P1_FLM = S.FLM OR :P1_FLM = '<All>') AND (:P1_REP = S.REP OR :P1_REP = '<All>'))
GROUP BY OPP_CATEGORY,
CATEGORY_SORT
ORDER BY CATEGORY_SORT desc




/*
///////
#Autonomous vs #Cloud vs #License 
//////
*/
SELECT 
Opportunity_Type,
SUM(Opps_Count)

FROM
(SELECT
    CASE 
        WHEN COMPENSATION_VIEW_LEVEL_0 = 'Tech Cloud' AND Autonomous_Opportunity > 1 THEN 'Autonomous'
        WHEN COMPENSATION_VIEW_LEVEL_0 = 'Tech Cloud'AND Autonomous_Opportunity = 0 THEN 'Cloud'
        WHEN COMPENSATION_VIEW_LEVEL_0 = 'Tech' THEN 'License' 
    END AS Opportunity_Type,
    Opps_Count
FROM
(SELECT      
OPPORTUNITY_ID,
PRIMARY_CAMPAIGN_SOURCE_CODE,
COMPENSATION_VIEW_LEVEL_0,
SUM(NVL(AUTONOMOUS_DATABASE_OLTP,0) + NVL(AUTONOMOUS_DATABASE_WAREHOUSE,0)) AS Autonomous_Opportunity,
COUNT(DISTINCT OPPORTUNITY_ID) as Opps_Count 
FROM LATEST_PIPE P
LEFT JOIN FLM_SALES S on S.REP = P.TERRITORY_OWNER_EMAIL
WHERE PRIMARY_CAMPAIGN_SOURCE_CODE = :P3_CODE AND (:P1_VP = S.VP OR :P1_VP = '<All>') AND (:P1_DIR = S.DIR OR :P1_DIR = '<All>') AND (:P1_FLM = S.FLM OR :P1_FLM = '<All>') AND (:P1_REP = S.REP OR :P1_REP = '<All>')
GROUP BY OPPORTUNITY_ID,
PRIMARY_CAMPAIGN_SOURCE_CODE,
COMPENSATION_VIEW_LEVEL_0))
GROUP BY Opportunity_Type




/*
///////
#Opp By Fiscal Quarter 
//////
*/
SELECT 
FISCAL_QUARTER,
COUNT(DISTINCT OPPORTUNITY_ID) as Opps_Count
FROM (
SELECT 
FISCAL_QUARTER,
REVENUE_LINE_ID,
OPPORTUNITY_ID,
PIPELINE_K,
CASE
    WHEN OPPORTUNITY_STATUS IN ('Closed','Pending Cancel','Lost') THEN 'Lost/Closed' 
    WHEN OPPORTUNITY_STATUS IN ('Won','Won Pending') THEN 'Won' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (10,0)  THEN 'Open 10%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (20,30)  THEN 'Open 20-30%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (40,50)  THEN 'Open 40-50%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (60,70,80,90,100)  THEN 'Open 60%+' 
    ELSE 'Error' 
END AS Opp_Category,
CASE
    WHEN OPPORTUNITY_STATUS IN ('Closed','Pending Cancel','Lost') THEN 1
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (10,0)  THEN 2
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (20,30)  THEN 3
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (40,50)  THEN 4
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (60,70,80,90,100)  THEN 5
    WHEN OPPORTUNITY_STATUS IN ('Won','Won Pending') THEN 6
    ELSE 0 
END AS Category_Sort
FROM LATEST_PIPE P
LEFT JOIN FLM_SALES S on S.REP = P.TERRITORY_OWNER_EMAIL
WHERE PRIMARY_CAMPAIGN_SOURCE_CODE = :P3_CODE AND (:P1_VP = S.VP OR :P1_VP = '<All>') AND (:P1_DIR = S.DIR OR :P1_DIR = '<All>') AND (:P1_FLM = S.FLM OR :P1_FLM = '<All>') AND (:P1_REP = S.REP OR :P1_REP = '<All>')
)
GROUP BY FISCAL_QUARTER
ORDER BY FISCAL_QUARTER asc




/*
///////
Pipeline By Status 
//////
*/
SELECT 
OPP_CATEGORY,
SUM(PIPELINE_K) as Pipeline,
CATEGORY_SORT
FROM (
SELECT 
FISCAL_QUARTER,
REVENUE_LINE_ID,
OPPORTUNITY_ID,
PIPELINE_K,
Case
    WHEN OPPORTUNITY_STATUS IN ('Closed','Pending Cancel','Lost') THEN 'Lost/Closed' 
    WHEN OPPORTUNITY_STATUS IN ('Won','Won Pending') THEN 'Won' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (10,0)  THEN 'Open 10%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (20,30)  THEN 'Open 20-30%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (40,50)  THEN 'Open 40-50%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (60,70,80,90,100)  THEN 'Open 60%+' 
    ELSE 'Error' 
END AS Opp_Category,
Case
    WHEN OPPORTUNITY_STATUS IN ('Closed','Pending Cancel','Lost') THEN 1
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (10,0)  THEN 2
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (20,30)  THEN 3
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (40,50)  THEN 4
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (60,70,80,90,100)  THEN 5
    WHEN OPPORTUNITY_STATUS IN ('Won','Won Pending') THEN 6
    ELSE 0 
END AS Category_Sort
FROM LATEST_PIPE P
LEFT JOIN FLM_SALES S on S.REP = P.TERRITORY_OWNER_EMAIL
WHERE PRIMARY_CAMPAIGN_SOURCE_CODE = :P3_CODE AND (:P1_VP = S.VP OR :P1_VP = '<All>') AND (:P1_DIR = S.DIR OR :P1_DIR = '<All>') AND (:P1_FLM = S.FLM OR :P1_FLM = '<All>') AND (:P1_REP = S.REP OR :P1_REP = '<All>'))
GROUP BY OPP_CATEGORY,
CATEGORY_SORT
ORDER BY CATEGORY_SORT desc





/*
///////
Pipeline Autonomous vs Cloud vs License
//////
*/
SELECT 
Opportunity_Type,
SUM(PIPELINE_K)

FROM
(SELECT
    CASE 
        WHEN COMPENSATION_VIEW_LEVEL_0 = 'Tech Cloud' AND Autonomous_Opportunity > 1 THEN 'Autonomous'
        WHEN COMPENSATION_VIEW_LEVEL_0 = 'Tech Cloud'AND Autonomous_Opportunity = 0 THEN 'Cloud'
        WHEN COMPENSATION_VIEW_LEVEL_0 = 'Tech' THEN 'License' 
    END AS Opportunity_Type,
    PIPELINE_K
FROM
(SELECT      
OPPORTUNITY_ID,
PRIMARY_CAMPAIGN_SOURCE_CODE,
COMPENSATION_VIEW_LEVEL_0,
SUM(NVL(AUTONOMOUS_DATABASE_OLTP,0) + NVL(AUTONOMOUS_DATABASE_WAREHOUSE,0)) AS Autonomous_Opportunity,
COUNT(DISTINCT OPPORTUNITY_ID) as Opps_Count,
PIPELINE_K
FROM LATEST_PIPE P
LEFT JOIN FLM_SALES S on S.REP = P.TERRITORY_OWNER_EMAIL
WHERE PRIMARY_CAMPAIGN_SOURCE_CODE = :P3_CODE AND (:P1_VP = S.VP OR :P1_VP = '<All>') AND (:P1_DIR = S.DIR OR :P1_DIR = '<All>') AND (:P1_FLM = S.FLM OR :P1_FLM = '<All>') AND (:P1_REP = S.REP OR :P1_REP = '<All>')
GROUP BY OPPORTUNITY_ID,
PRIMARY_CAMPAIGN_SOURCE_CODE,
COMPENSATION_VIEW_LEVEL_0,PIPELINE_K))
GROUP BY Opportunity_Type




/*
///////
Pipeline By Fiscal Quarter 
//////
*/
SELECT 
FISCAL_QUARTER,
SUM(PIPELINE_K) as Pipeline
FROM (
SELECT 
FISCAL_QUARTER,
REVENUE_LINE_ID,
OPPORTUNITY_ID,
PIPELINE_K,
CASE
    WHEN OPPORTUNITY_STATUS IN ('Closed','Pending Cancel','Lost') THEN 'Lost/Closed' 
    WHEN OPPORTUNITY_STATUS IN ('Won','Won Pending') THEN 'Won' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (10,0)  THEN 'Open 10%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (20,30)  THEN 'Open 20-30%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (40,50)  THEN 'Open 40-50%' 
    WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (60,70,80,90,100)  THEN 'Open 60%+' 
    ELSE 'Error' 
END AS Opp_Category,
CASE
WHEN OPPORTUNITY_STATUS IN ('Closed','Pending Cancel','Lost') THEN 1
WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (10,0)  THEN 2
WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (20,30)  THEN 3
WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (40,50)  THEN 4
WHEN OPPORTUNITY_STATUS = 'Open' AND OPTY_PROBABILITY IN (60,70,80,90,100)  THEN 5
WHEN OPPORTUNITY_STATUS IN ('Won','Won Pending') THEN 6
ELSE 0 END as Category_Sort
FROM LATEST_PIPE P
LEFT JOIN FLM_SALES S on S.REP = P.TERRITORY_OWNER_EMAIL
WHERE PRIMARY_CAMPAIGN_SOURCE_CODE = :P3_CODE AND (:P1_VP = S.VP OR :P1_VP = '<All>') AND (:P1_DIR = S.DIR OR :P1_DIR = '<All>') AND (:P1_FLM = S.FLM OR :P1_FLM = '<All>') AND (:P1_REP = S.REP OR :P1_REP = '<All>')
)
GROUP BY FISCAL_QUARTER
ORDER BY FISCAL_QUARTER asc


